# Generated by Django 4.2.7 on 2023-11-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
