# Generated by Django 4.2.7 on 2023-11-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmodel',
            name='datetime',
        ),
        migrations.AddField(
            model_name='assessmentmodel',
            name='timestamp',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
