# Generated by Django 4.2.4 on 2023-09-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='q10',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q2',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q3',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q4',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q5',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q6',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q7',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q8',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AddField(
            model_name='questions',
            name='q9',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q1',
            field=models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Not Good', max_length=15),
        ),
    ]
